/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 27
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 17
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_DQUOTE = 1,
  anon_sym_PERCENT_PERCENT = 2,
  anon_sym_PERCENT = 3,
  sym_type = 4,
  sym_flags = 5,
  sym_width = 6,
  sym_precision = 7,
  anon_sym_hh = 8,
  anon_sym_h = 9,
  anon_sym_j = 10,
  anon_sym_l = 11,
  anon_sym_L = 12,
  anon_sym_ll = 13,
  anon_sym_t = 14,
  anon_sym_w = 15,
  anon_sym_z = 16,
  anon_sym_I = 17,
  anon_sym_I32 = 18,
  anon_sym_I64 = 19,
  sym_escape_sequence = 20,
  sym_text = 21,
  sym_format_string = 22,
  sym_text_parts = 23,
  sym_format = 24,
  sym_size = 25,
  aux_sym_format_string_repeat1 = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_PERCENT_PERCENT] = "%%",
  [anon_sym_PERCENT] = "%",
  [sym_type] = "type",
  [sym_flags] = "flags",
  [sym_width] = "width",
  [sym_precision] = "precision",
  [anon_sym_hh] = "hh",
  [anon_sym_h] = "h",
  [anon_sym_j] = "j",
  [anon_sym_l] = "l",
  [anon_sym_L] = "L",
  [anon_sym_ll] = "ll",
  [anon_sym_t] = "t",
  [anon_sym_w] = "w",
  [anon_sym_z] = "z",
  [anon_sym_I] = "I",
  [anon_sym_I32] = "I32",
  [anon_sym_I64] = "I64",
  [sym_escape_sequence] = "escape_sequence",
  [sym_text] = "text",
  [sym_format_string] = "format_string",
  [sym_text_parts] = "text_parts",
  [sym_format] = "format",
  [sym_size] = "size",
  [aux_sym_format_string_repeat1] = "format_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_PERCENT_PERCENT] = anon_sym_PERCENT_PERCENT,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_type] = sym_type,
  [sym_flags] = sym_flags,
  [sym_width] = sym_width,
  [sym_precision] = sym_precision,
  [anon_sym_hh] = anon_sym_hh,
  [anon_sym_h] = anon_sym_h,
  [anon_sym_j] = anon_sym_j,
  [anon_sym_l] = anon_sym_l,
  [anon_sym_L] = anon_sym_L,
  [anon_sym_ll] = anon_sym_ll,
  [anon_sym_t] = anon_sym_t,
  [anon_sym_w] = anon_sym_w,
  [anon_sym_z] = anon_sym_z,
  [anon_sym_I] = anon_sym_I,
  [anon_sym_I32] = anon_sym_I32,
  [anon_sym_I64] = anon_sym_I64,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_text] = sym_text,
  [sym_format_string] = sym_format_string,
  [sym_text_parts] = sym_text_parts,
  [sym_format] = sym_format,
  [sym_size] = sym_size,
  [aux_sym_format_string_repeat1] = aux_sym_format_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_flags] = {
    .visible = true,
    .named = true,
  },
  [sym_width] = {
    .visible = true,
    .named = true,
  },
  [sym_precision] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_hh] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_h] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_j] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_l] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_L] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ll] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_w] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_z] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_I] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_I32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_I64] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_format_string] = {
    .visible = true,
    .named = true,
  },
  [sym_text_parts] = {
    .visible = true,
    .named = true,
  },
  [sym_format] = {
    .visible = true,
    .named = true,
  },
  [sym_size] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_format_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_flags = 1,
  field_precision = 2,
  field_size = 3,
  field_type = 4,
  field_width = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_flags] = "flags",
  [field_precision] = "precision",
  [field_size] = "size",
  [field_type] = "type",
  [field_width] = "width",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 3},
  [7] = {.index = 12, .length = 3},
  [8] = {.index = 15, .length = 3},
  [9] = {.index = 18, .length = 3},
  [10] = {.index = 21, .length = 3},
  [11] = {.index = 24, .length = 3},
  [12] = {.index = 27, .length = 4},
  [13] = {.index = 31, .length = 4},
  [14] = {.index = 35, .length = 4},
  [15] = {.index = 39, .length = 4},
  [16] = {.index = 43, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 1},
  [1] =
    {field_flags, 1},
    {field_type, 2},
  [3] =
    {field_type, 2},
    {field_width, 1},
  [5] =
    {field_precision, 1},
    {field_type, 2},
  [7] =
    {field_size, 1},
    {field_type, 2},
  [9] =
    {field_flags, 1},
    {field_type, 3},
    {field_width, 2},
  [12] =
    {field_flags, 1},
    {field_precision, 2},
    {field_type, 3},
  [15] =
    {field_flags, 1},
    {field_size, 2},
    {field_type, 3},
  [18] =
    {field_precision, 2},
    {field_type, 3},
    {field_width, 1},
  [21] =
    {field_size, 2},
    {field_type, 3},
    {field_width, 1},
  [24] =
    {field_precision, 1},
    {field_size, 2},
    {field_type, 3},
  [27] =
    {field_flags, 1},
    {field_precision, 3},
    {field_type, 4},
    {field_width, 2},
  [31] =
    {field_flags, 1},
    {field_size, 3},
    {field_type, 4},
    {field_width, 2},
  [35] =
    {field_flags, 1},
    {field_precision, 2},
    {field_size, 3},
    {field_type, 4},
  [39] =
    {field_precision, 2},
    {field_size, 3},
    {field_type, 4},
    {field_width, 1},
  [43] =
    {field_flags, 1},
    {field_precision, 3},
    {field_size, 4},
    {field_type, 5},
    {field_width, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
};

static const TSCharacterRange sym_escape_sequence_character_set_1[] = {
  {'"', '"'}, {'\'', '\''}, {'0', '7'}, {'?', '?'}, {'U', 'U'}, {'\\', '\\'}, {'a', 'b'}, {'f', 'f'},
  {'n', 'n'}, {'r', 'r'}, {'t', 'v'}, {'x', 'x'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '"') ADVANCE(16);
      if (lookahead == '%') ADVANCE(18);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '.') ADVANCE(24);
      if (lookahead == 'I') ADVANCE(35);
      if (lookahead == 'L') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == 'h') ADVANCE(27);
      if (lookahead == 'j') ADVANCE(28);
      if (lookahead == 'l') ADVANCE(29);
      if (lookahead == 't') ADVANCE(32);
      if (lookahead == 'w') ADVANCE(33);
      if (lookahead == 'z') ADVANCE(34);
      if (lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '0') ADVANCE(20);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == '"') ADVANCE(16);
      if (lookahead == '%') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == '2') ADVANCE(36);
      END_STATE();
    case 4:
      if (lookahead == '4') ADVANCE(37);
      END_STATE();
    case 5:
      if (lookahead == 'U') ADVANCE(14);
      if (lookahead == 'u') ADVANCE(10);
      if (lookahead == 'x') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(40);
      if (set_contains(sym_escape_sequence_character_set_1, 12, lookahead)) ADVANCE(38);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(8);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PERCENT_PERCENT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '%') ADVANCE(17);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_type);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_flags);
      if (lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '0') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_width);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_width);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_precision);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_precision);
      if (lookahead == '*') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_precision);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_hh);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_h);
      if (lookahead == 'h') ADVANCE(26);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_j);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_l);
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_L);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_ll);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_t);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_w);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_z);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_I);
      if (lookahead == '3') ADVANCE(3);
      if (lookahead == '6') ADVANCE(4);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_I32);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_I64);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(39);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '%' &&
          lookahead != '\\') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '%' &&
          lookahead != '\\') ADVANCE(43);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_PERCENT_PERCENT] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
    [sym_flags] = ACTIONS(1),
    [sym_width] = ACTIONS(1),
    [sym_precision] = ACTIONS(1),
    [anon_sym_hh] = ACTIONS(1),
    [anon_sym_h] = ACTIONS(1),
    [anon_sym_j] = ACTIONS(1),
    [anon_sym_l] = ACTIONS(1),
    [anon_sym_L] = ACTIONS(1),
    [anon_sym_ll] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [anon_sym_w] = ACTIONS(1),
    [anon_sym_z] = ACTIONS(1),
    [anon_sym_I] = ACTIONS(1),
    [anon_sym_I32] = ACTIONS(1),
    [anon_sym_I64] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_format_string] = STATE(30),
    [anon_sym_DQUOTE] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_size] = STATE(37),
    [sym_type] = ACTIONS(5),
    [sym_flags] = ACTIONS(7),
    [sym_width] = ACTIONS(9),
    [sym_precision] = ACTIONS(11),
    [anon_sym_hh] = ACTIONS(13),
    [anon_sym_h] = ACTIONS(15),
    [anon_sym_j] = ACTIONS(13),
    [anon_sym_l] = ACTIONS(15),
    [anon_sym_L] = ACTIONS(13),
    [anon_sym_ll] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [anon_sym_w] = ACTIONS(13),
    [anon_sym_z] = ACTIONS(13),
    [anon_sym_I] = ACTIONS(15),
    [anon_sym_I32] = ACTIONS(13),
    [anon_sym_I64] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_size] = STATE(34),
    [sym_type] = ACTIONS(17),
    [sym_width] = ACTIONS(19),
    [sym_precision] = ACTIONS(21),
    [anon_sym_hh] = ACTIONS(13),
    [anon_sym_h] = ACTIONS(15),
    [anon_sym_j] = ACTIONS(13),
    [anon_sym_l] = ACTIONS(15),
    [anon_sym_L] = ACTIONS(13),
    [anon_sym_ll] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [anon_sym_w] = ACTIONS(13),
    [anon_sym_z] = ACTIONS(13),
    [anon_sym_I] = ACTIONS(15),
    [anon_sym_I32] = ACTIONS(13),
    [anon_sym_I64] = ACTIONS(13),
  },
  [STATE(4)] = {
    [sym_size] = STATE(41),
    [sym_type] = ACTIONS(23),
    [sym_precision] = ACTIONS(25),
    [anon_sym_hh] = ACTIONS(13),
    [anon_sym_h] = ACTIONS(15),
    [anon_sym_j] = ACTIONS(13),
    [anon_sym_l] = ACTIONS(15),
    [anon_sym_L] = ACTIONS(13),
    [anon_sym_ll] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [anon_sym_w] = ACTIONS(13),
    [anon_sym_z] = ACTIONS(13),
    [anon_sym_I] = ACTIONS(15),
    [anon_sym_I32] = ACTIONS(13),
    [anon_sym_I64] = ACTIONS(13),
  },
  [STATE(5)] = {
    [sym_size] = STATE(31),
    [sym_type] = ACTIONS(27),
    [sym_precision] = ACTIONS(29),
    [anon_sym_hh] = ACTIONS(13),
    [anon_sym_h] = ACTIONS(15),
    [anon_sym_j] = ACTIONS(13),
    [anon_sym_l] = ACTIONS(15),
    [anon_sym_L] = ACTIONS(13),
    [anon_sym_ll] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [anon_sym_w] = ACTIONS(13),
    [anon_sym_z] = ACTIONS(13),
    [anon_sym_I] = ACTIONS(15),
    [anon_sym_I32] = ACTIONS(13),
    [anon_sym_I64] = ACTIONS(13),
  },
  [STATE(6)] = {
    [sym_size] = STATE(33),
    [sym_type] = ACTIONS(31),
    [anon_sym_hh] = ACTIONS(13),
    [anon_sym_h] = ACTIONS(15),
    [anon_sym_j] = ACTIONS(13),
    [anon_sym_l] = ACTIONS(15),
    [anon_sym_L] = ACTIONS(13),
    [anon_sym_ll] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [anon_sym_w] = ACTIONS(13),
    [anon_sym_z] = ACTIONS(13),
    [anon_sym_I] = ACTIONS(15),
    [anon_sym_I32] = ACTIONS(13),
    [anon_sym_I64] = ACTIONS(13),
  },
  [STATE(7)] = {
    [sym_size] = STATE(38),
    [sym_type] = ACTIONS(33),
    [anon_sym_hh] = ACTIONS(13),
    [anon_sym_h] = ACTIONS(15),
    [anon_sym_j] = ACTIONS(13),
    [anon_sym_l] = ACTIONS(15),
    [anon_sym_L] = ACTIONS(13),
    [anon_sym_ll] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [anon_sym_w] = ACTIONS(13),
    [anon_sym_z] = ACTIONS(13),
    [anon_sym_I] = ACTIONS(15),
    [anon_sym_I32] = ACTIONS(13),
    [anon_sym_I64] = ACTIONS(13),
  },
  [STATE(8)] = {
    [sym_size] = STATE(40),
    [sym_type] = ACTIONS(35),
    [anon_sym_hh] = ACTIONS(13),
    [anon_sym_h] = ACTIONS(15),
    [anon_sym_j] = ACTIONS(13),
    [anon_sym_l] = ACTIONS(15),
    [anon_sym_L] = ACTIONS(13),
    [anon_sym_ll] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [anon_sym_w] = ACTIONS(13),
    [anon_sym_z] = ACTIONS(13),
    [anon_sym_I] = ACTIONS(15),
    [anon_sym_I32] = ACTIONS(13),
    [anon_sym_I64] = ACTIONS(13),
  },
  [STATE(9)] = {
    [sym_size] = STATE(39),
    [sym_type] = ACTIONS(37),
    [anon_sym_hh] = ACTIONS(13),
    [anon_sym_h] = ACTIONS(15),
    [anon_sym_j] = ACTIONS(13),
    [anon_sym_l] = ACTIONS(15),
    [anon_sym_L] = ACTIONS(13),
    [anon_sym_ll] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [anon_sym_w] = ACTIONS(13),
    [anon_sym_z] = ACTIONS(13),
    [anon_sym_I] = ACTIONS(15),
    [anon_sym_I32] = ACTIONS(13),
    [anon_sym_I64] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(39), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 1,
      anon_sym_PERCENT,
    ACTIONS(47), 1,
      sym_text,
    STATE(17), 1,
      sym_format,
    ACTIONS(41), 2,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
    STATE(10), 2,
      sym_text_parts,
      aux_sym_format_string_repeat1,
  [21] = 6,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(54), 1,
      anon_sym_PERCENT,
    ACTIONS(56), 1,
      sym_text,
    STATE(17), 1,
      sym_format,
    ACTIONS(52), 2,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
    STATE(10), 2,
      sym_text_parts,
      aux_sym_format_string_repeat1,
  [42] = 6,
    ACTIONS(54), 1,
      anon_sym_PERCENT,
    ACTIONS(56), 1,
      sym_text,
    ACTIONS(58), 1,
      anon_sym_DQUOTE,
    STATE(17), 1,
      sym_format,
    ACTIONS(52), 2,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
    STATE(11), 2,
      sym_text_parts,
      aux_sym_format_string_repeat1,
  [63] = 2,
    ACTIONS(62), 1,
      sym_text,
    ACTIONS(60), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [73] = 2,
    ACTIONS(66), 1,
      sym_text,
    ACTIONS(64), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [83] = 2,
    ACTIONS(70), 1,
      sym_text,
    ACTIONS(68), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [93] = 2,
    ACTIONS(74), 1,
      sym_text,
    ACTIONS(72), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [103] = 2,
    ACTIONS(78), 1,
      sym_text,
    ACTIONS(76), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [113] = 2,
    ACTIONS(82), 1,
      sym_text,
    ACTIONS(80), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [123] = 2,
    ACTIONS(86), 1,
      sym_text,
    ACTIONS(84), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [133] = 2,
    ACTIONS(90), 1,
      sym_text,
    ACTIONS(88), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [143] = 2,
    ACTIONS(94), 1,
      sym_text,
    ACTIONS(92), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [153] = 2,
    ACTIONS(98), 1,
      sym_text,
    ACTIONS(96), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [163] = 2,
    ACTIONS(102), 1,
      sym_text,
    ACTIONS(100), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [173] = 2,
    ACTIONS(106), 1,
      sym_text,
    ACTIONS(104), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [183] = 2,
    ACTIONS(110), 1,
      sym_text,
    ACTIONS(108), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [193] = 2,
    ACTIONS(114), 1,
      sym_text,
    ACTIONS(112), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [203] = 2,
    ACTIONS(118), 1,
      sym_text,
    ACTIONS(116), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [213] = 2,
    ACTIONS(122), 1,
      sym_text,
    ACTIONS(120), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [223] = 2,
    ACTIONS(126), 1,
      sym_text,
    ACTIONS(124), 4,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENT,
      sym_escape_sequence,
  [233] = 1,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
  [237] = 1,
    ACTIONS(130), 1,
      sym_type,
  [241] = 1,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
  [245] = 1,
    ACTIONS(134), 1,
      sym_type,
  [249] = 1,
    ACTIONS(136), 1,
      sym_type,
  [253] = 1,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
  [257] = 1,
    ACTIONS(140), 1,
      sym_type,
  [261] = 1,
    ACTIONS(142), 1,
      sym_type,
  [265] = 1,
    ACTIONS(144), 1,
      sym_type,
  [269] = 1,
    ACTIONS(146), 1,
      sym_type,
  [273] = 1,
    ACTIONS(148), 1,
      sym_type,
  [277] = 1,
    ACTIONS(150), 1,
      sym_type,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 21,
  [SMALL_STATE(12)] = 42,
  [SMALL_STATE(13)] = 63,
  [SMALL_STATE(14)] = 73,
  [SMALL_STATE(15)] = 83,
  [SMALL_STATE(16)] = 93,
  [SMALL_STATE(17)] = 103,
  [SMALL_STATE(18)] = 113,
  [SMALL_STATE(19)] = 123,
  [SMALL_STATE(20)] = 133,
  [SMALL_STATE(21)] = 143,
  [SMALL_STATE(22)] = 153,
  [SMALL_STATE(23)] = 163,
  [SMALL_STATE(24)] = 173,
  [SMALL_STATE(25)] = 183,
  [SMALL_STATE(26)] = 193,
  [SMALL_STATE(27)] = 203,
  [SMALL_STATE(28)] = 213,
  [SMALL_STATE(29)] = 223,
  [SMALL_STATE(30)] = 233,
  [SMALL_STATE(31)] = 237,
  [SMALL_STATE(32)] = 241,
  [SMALL_STATE(33)] = 245,
  [SMALL_STATE(34)] = 249,
  [SMALL_STATE(35)] = 253,
  [SMALL_STATE(36)] = 257,
  [SMALL_STATE(37)] = 261,
  [SMALL_STATE(38)] = 265,
  [SMALL_STATE(39)] = 269,
  [SMALL_STATE(40)] = 273,
  [SMALL_STATE(41)] = 277,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 4, 0, 11),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 11),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 4, 0, 6),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 6),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 2, 0, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 2, 0, 1),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 3, 0, 2),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 3, 0, 2),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_parts, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_parts, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 3, 0, 3),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 3, 0, 3),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 3, 0, 5),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 3, 0, 5),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 3, 0, 4),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 3, 0, 4),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 5, 0, 15),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 5, 0, 15),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 4, 0, 7),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 7),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 4, 0, 8),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 8),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 4, 0, 10),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 10),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 4, 0, 9),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 9),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 5, 0, 14),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 5, 0, 14),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 5, 0, 13),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 5, 0, 13),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 5, 0, 12),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 5, 0, 12),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 6, 0, 16),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 6, 0, 16),
  [128] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_size, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_printf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
