/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 17
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_PERCENT_PERCENT = 1,
  anon_sym_PERCENT = 2,
  sym_type = 3,
  sym_flags = 4,
  sym_width = 5,
  sym_precision = 6,
  anon_sym_hh = 7,
  anon_sym_h = 8,
  anon_sym_j = 9,
  anon_sym_l = 10,
  anon_sym_L = 11,
  anon_sym_ll = 12,
  anon_sym_t = 13,
  anon_sym_w = 14,
  anon_sym_z = 15,
  anon_sym_I = 16,
  anon_sym_I32 = 17,
  anon_sym_I64 = 18,
  sym_escape_sequence = 19,
  sym_text = 20,
  sym_format_string = 21,
  sym_text_parts = 22,
  sym_format = 23,
  sym_size = 24,
  aux_sym_format_string_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PERCENT_PERCENT] = "%%",
  [anon_sym_PERCENT] = "%",
  [sym_type] = "type",
  [sym_flags] = "flags",
  [sym_width] = "width",
  [sym_precision] = "precision",
  [anon_sym_hh] = "hh",
  [anon_sym_h] = "h",
  [anon_sym_j] = "j",
  [anon_sym_l] = "l",
  [anon_sym_L] = "L",
  [anon_sym_ll] = "ll",
  [anon_sym_t] = "t",
  [anon_sym_w] = "w",
  [anon_sym_z] = "z",
  [anon_sym_I] = "I",
  [anon_sym_I32] = "I32",
  [anon_sym_I64] = "I64",
  [sym_escape_sequence] = "escape_sequence",
  [sym_text] = "text",
  [sym_format_string] = "format_string",
  [sym_text_parts] = "text_parts",
  [sym_format] = "format",
  [sym_size] = "size",
  [aux_sym_format_string_repeat1] = "format_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PERCENT_PERCENT] = anon_sym_PERCENT_PERCENT,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_type] = sym_type,
  [sym_flags] = sym_flags,
  [sym_width] = sym_width,
  [sym_precision] = sym_precision,
  [anon_sym_hh] = anon_sym_hh,
  [anon_sym_h] = anon_sym_h,
  [anon_sym_j] = anon_sym_j,
  [anon_sym_l] = anon_sym_l,
  [anon_sym_L] = anon_sym_L,
  [anon_sym_ll] = anon_sym_ll,
  [anon_sym_t] = anon_sym_t,
  [anon_sym_w] = anon_sym_w,
  [anon_sym_z] = anon_sym_z,
  [anon_sym_I] = anon_sym_I,
  [anon_sym_I32] = anon_sym_I32,
  [anon_sym_I64] = anon_sym_I64,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_text] = sym_text,
  [sym_format_string] = sym_format_string,
  [sym_text_parts] = sym_text_parts,
  [sym_format] = sym_format,
  [sym_size] = sym_size,
  [aux_sym_format_string_repeat1] = aux_sym_format_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PERCENT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_flags] = {
    .visible = true,
    .named = true,
  },
  [sym_width] = {
    .visible = true,
    .named = true,
  },
  [sym_precision] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_hh] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_h] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_j] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_l] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_L] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ll] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_w] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_z] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_I] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_I32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_I64] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_format_string] = {
    .visible = true,
    .named = true,
  },
  [sym_text_parts] = {
    .visible = true,
    .named = true,
  },
  [sym_format] = {
    .visible = true,
    .named = true,
  },
  [sym_size] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_format_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_flags = 1,
  field_precision = 2,
  field_size = 3,
  field_type = 4,
  field_width = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_flags] = "flags",
  [field_precision] = "precision",
  [field_size] = "size",
  [field_type] = "type",
  [field_width] = "width",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 3},
  [7] = {.index = 12, .length = 3},
  [8] = {.index = 15, .length = 3},
  [9] = {.index = 18, .length = 3},
  [10] = {.index = 21, .length = 3},
  [11] = {.index = 24, .length = 3},
  [12] = {.index = 27, .length = 4},
  [13] = {.index = 31, .length = 4},
  [14] = {.index = 35, .length = 4},
  [15] = {.index = 39, .length = 4},
  [16] = {.index = 43, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 1},
  [1] =
    {field_flags, 1},
    {field_type, 2},
  [3] =
    {field_type, 2},
    {field_width, 1},
  [5] =
    {field_precision, 1},
    {field_type, 2},
  [7] =
    {field_size, 1},
    {field_type, 2},
  [9] =
    {field_flags, 1},
    {field_type, 3},
    {field_width, 2},
  [12] =
    {field_flags, 1},
    {field_precision, 2},
    {field_type, 3},
  [15] =
    {field_flags, 1},
    {field_size, 2},
    {field_type, 3},
  [18] =
    {field_precision, 2},
    {field_type, 3},
    {field_width, 1},
  [21] =
    {field_size, 2},
    {field_type, 3},
    {field_width, 1},
  [24] =
    {field_precision, 1},
    {field_size, 2},
    {field_type, 3},
  [27] =
    {field_flags, 1},
    {field_precision, 3},
    {field_type, 4},
    {field_width, 2},
  [31] =
    {field_flags, 1},
    {field_size, 3},
    {field_type, 4},
    {field_width, 2},
  [35] =
    {field_flags, 1},
    {field_precision, 2},
    {field_size, 3},
    {field_type, 4},
  [39] =
    {field_precision, 2},
    {field_size, 3},
    {field_type, 4},
    {field_width, 1},
  [43] =
    {field_flags, 1},
    {field_precision, 3},
    {field_size, 4},
    {field_type, 5},
    {field_width, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
};

static const TSCharacterRange sym_escape_sequence_character_set_1[] = {
  {'"', '"'}, {'\'', '\''}, {'0', '7'}, {'?', '?'}, {'U', 'U'}, {'\\', '\\'}, {'a', 'b'}, {'f', 'f'},
  {'n', 'n'}, {'r', 'r'}, {'t', 'v'}, {'x', 'x'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == 'I') ADVANCE(34);
      if (lookahead == 'L') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == 'h') ADVANCE(26);
      if (lookahead == 'j') ADVANCE(27);
      if (lookahead == 'l') ADVANCE(28);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == 'w') ADVANCE(32);
      if (lookahead == 'z') ADVANCE(33);
      if (lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == '\'' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '0') ADVANCE(19);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == '2') ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '4') ADVANCE(36);
      END_STATE();
    case 4:
      if (lookahead == 'U') ADVANCE(13);
      if (lookahead == 'u') ADVANCE(9);
      if (lookahead == 'x') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(39);
      if (set_contains(sym_escape_sequence_character_set_1, 12, lookahead)) ADVANCE(37);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(5);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(7);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(8);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(14);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_PERCENT_PERCENT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '%') ADVANCE(16);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_type);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_flags);
      if (lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == '\'' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '0') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_width);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_width);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_precision);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_precision);
      if (lookahead == '*') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_precision);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_hh);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_h);
      if (lookahead == 'h') ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_j);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_l);
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_L);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_ll);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_t);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_w);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_z);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_I);
      if (lookahead == '3') ADVANCE(2);
      if (lookahead == '6') ADVANCE(3);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_I32);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_I64);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '%' &&
          lookahead != '\\') ADVANCE(41);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 14},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 14},
  [25] = {.lex_state = 14},
  [26] = {.lex_state = 14},
  [27] = {.lex_state = 14},
  [28] = {.lex_state = 14},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PERCENT_PERCENT] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
    [sym_flags] = ACTIONS(1),
    [sym_width] = ACTIONS(1),
    [sym_precision] = ACTIONS(1),
    [anon_sym_hh] = ACTIONS(1),
    [anon_sym_h] = ACTIONS(1),
    [anon_sym_j] = ACTIONS(1),
    [anon_sym_l] = ACTIONS(1),
    [anon_sym_L] = ACTIONS(1),
    [anon_sym_ll] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [anon_sym_w] = ACTIONS(1),
    [anon_sym_z] = ACTIONS(1),
    [anon_sym_I] = ACTIONS(1),
    [anon_sym_I32] = ACTIONS(1),
    [anon_sym_I64] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_format_string] = STATE(35),
    [sym_text_parts] = STATE(10),
    [sym_format] = STATE(14),
    [aux_sym_format_string_repeat1] = STATE(10),
    [anon_sym_PERCENT_PERCENT] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
    [sym_escape_sequence] = ACTIONS(3),
    [sym_text] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_size] = STATE(33),
    [sym_type] = ACTIONS(7),
    [sym_flags] = ACTIONS(9),
    [sym_width] = ACTIONS(11),
    [sym_precision] = ACTIONS(13),
    [anon_sym_hh] = ACTIONS(15),
    [anon_sym_h] = ACTIONS(17),
    [anon_sym_j] = ACTIONS(15),
    [anon_sym_l] = ACTIONS(17),
    [anon_sym_L] = ACTIONS(15),
    [anon_sym_ll] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(15),
    [anon_sym_w] = ACTIONS(15),
    [anon_sym_z] = ACTIONS(15),
    [anon_sym_I] = ACTIONS(17),
    [anon_sym_I32] = ACTIONS(15),
    [anon_sym_I64] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_size] = STATE(31),
    [sym_type] = ACTIONS(19),
    [sym_width] = ACTIONS(21),
    [sym_precision] = ACTIONS(23),
    [anon_sym_hh] = ACTIONS(15),
    [anon_sym_h] = ACTIONS(17),
    [anon_sym_j] = ACTIONS(15),
    [anon_sym_l] = ACTIONS(17),
    [anon_sym_L] = ACTIONS(15),
    [anon_sym_ll] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(15),
    [anon_sym_w] = ACTIONS(15),
    [anon_sym_z] = ACTIONS(15),
    [anon_sym_I] = ACTIONS(17),
    [anon_sym_I32] = ACTIONS(15),
    [anon_sym_I64] = ACTIONS(15),
  },
  [STATE(4)] = {
    [sym_size] = STATE(30),
    [sym_type] = ACTIONS(25),
    [sym_precision] = ACTIONS(27),
    [anon_sym_hh] = ACTIONS(15),
    [anon_sym_h] = ACTIONS(17),
    [anon_sym_j] = ACTIONS(15),
    [anon_sym_l] = ACTIONS(17),
    [anon_sym_L] = ACTIONS(15),
    [anon_sym_ll] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(15),
    [anon_sym_w] = ACTIONS(15),
    [anon_sym_z] = ACTIONS(15),
    [anon_sym_I] = ACTIONS(17),
    [anon_sym_I32] = ACTIONS(15),
    [anon_sym_I64] = ACTIONS(15),
  },
  [STATE(5)] = {
    [sym_size] = STATE(34),
    [sym_type] = ACTIONS(29),
    [sym_precision] = ACTIONS(31),
    [anon_sym_hh] = ACTIONS(15),
    [anon_sym_h] = ACTIONS(17),
    [anon_sym_j] = ACTIONS(15),
    [anon_sym_l] = ACTIONS(17),
    [anon_sym_L] = ACTIONS(15),
    [anon_sym_ll] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(15),
    [anon_sym_w] = ACTIONS(15),
    [anon_sym_z] = ACTIONS(15),
    [anon_sym_I] = ACTIONS(17),
    [anon_sym_I32] = ACTIONS(15),
    [anon_sym_I64] = ACTIONS(15),
  },
  [STATE(6)] = {
    [sym_size] = STATE(32),
    [sym_type] = ACTIONS(33),
    [anon_sym_hh] = ACTIONS(15),
    [anon_sym_h] = ACTIONS(17),
    [anon_sym_j] = ACTIONS(15),
    [anon_sym_l] = ACTIONS(17),
    [anon_sym_L] = ACTIONS(15),
    [anon_sym_ll] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(15),
    [anon_sym_w] = ACTIONS(15),
    [anon_sym_z] = ACTIONS(15),
    [anon_sym_I] = ACTIONS(17),
    [anon_sym_I32] = ACTIONS(15),
    [anon_sym_I64] = ACTIONS(15),
  },
  [STATE(7)] = {
    [sym_size] = STATE(36),
    [sym_type] = ACTIONS(35),
    [anon_sym_hh] = ACTIONS(15),
    [anon_sym_h] = ACTIONS(17),
    [anon_sym_j] = ACTIONS(15),
    [anon_sym_l] = ACTIONS(17),
    [anon_sym_L] = ACTIONS(15),
    [anon_sym_ll] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(15),
    [anon_sym_w] = ACTIONS(15),
    [anon_sym_z] = ACTIONS(15),
    [anon_sym_I] = ACTIONS(17),
    [anon_sym_I32] = ACTIONS(15),
    [anon_sym_I64] = ACTIONS(15),
  },
  [STATE(8)] = {
    [sym_size] = STATE(38),
    [sym_type] = ACTIONS(37),
    [anon_sym_hh] = ACTIONS(15),
    [anon_sym_h] = ACTIONS(17),
    [anon_sym_j] = ACTIONS(15),
    [anon_sym_l] = ACTIONS(17),
    [anon_sym_L] = ACTIONS(15),
    [anon_sym_ll] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(15),
    [anon_sym_w] = ACTIONS(15),
    [anon_sym_z] = ACTIONS(15),
    [anon_sym_I] = ACTIONS(17),
    [anon_sym_I32] = ACTIONS(15),
    [anon_sym_I64] = ACTIONS(15),
  },
  [STATE(9)] = {
    [sym_size] = STATE(37),
    [sym_type] = ACTIONS(39),
    [anon_sym_hh] = ACTIONS(15),
    [anon_sym_h] = ACTIONS(17),
    [anon_sym_j] = ACTIONS(15),
    [anon_sym_l] = ACTIONS(17),
    [anon_sym_L] = ACTIONS(15),
    [anon_sym_ll] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(15),
    [anon_sym_w] = ACTIONS(15),
    [anon_sym_z] = ACTIONS(15),
    [anon_sym_I] = ACTIONS(17),
    [anon_sym_I32] = ACTIONS(15),
    [anon_sym_I64] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      anon_sym_PERCENT,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      sym_format,
    STATE(11), 2,
      sym_text_parts,
      aux_sym_format_string_repeat1,
    ACTIONS(3), 3,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [19] = 5,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 1,
      anon_sym_PERCENT,
    STATE(14), 1,
      sym_format,
    STATE(11), 2,
      sym_text_parts,
      aux_sym_format_string_repeat1,
    ACTIONS(45), 3,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [38] = 2,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(51), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [48] = 2,
    ACTIONS(57), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [58] = 2,
    ACTIONS(61), 1,
      anon_sym_PERCENT,
    ACTIONS(59), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [68] = 2,
    ACTIONS(65), 1,
      anon_sym_PERCENT,
    ACTIONS(63), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [78] = 2,
    ACTIONS(69), 1,
      anon_sym_PERCENT,
    ACTIONS(67), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [88] = 2,
    ACTIONS(73), 1,
      anon_sym_PERCENT,
    ACTIONS(71), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [98] = 2,
    ACTIONS(77), 1,
      anon_sym_PERCENT,
    ACTIONS(75), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [108] = 2,
    ACTIONS(81), 1,
      anon_sym_PERCENT,
    ACTIONS(79), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [118] = 2,
    ACTIONS(85), 1,
      anon_sym_PERCENT,
    ACTIONS(83), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [128] = 2,
    ACTIONS(89), 1,
      anon_sym_PERCENT,
    ACTIONS(87), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [138] = 2,
    ACTIONS(93), 1,
      anon_sym_PERCENT,
    ACTIONS(91), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [148] = 2,
    ACTIONS(97), 1,
      anon_sym_PERCENT,
    ACTIONS(95), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [158] = 2,
    ACTIONS(101), 1,
      anon_sym_PERCENT,
    ACTIONS(99), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [168] = 2,
    ACTIONS(105), 1,
      anon_sym_PERCENT,
    ACTIONS(103), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [178] = 2,
    ACTIONS(109), 1,
      anon_sym_PERCENT,
    ACTIONS(107), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [188] = 2,
    ACTIONS(113), 1,
      anon_sym_PERCENT,
    ACTIONS(111), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [198] = 2,
    ACTIONS(117), 1,
      anon_sym_PERCENT,
    ACTIONS(115), 4,
      ts_builtin_sym_end,
      anon_sym_PERCENT_PERCENT,
      sym_escape_sequence,
      sym_text,
  [208] = 1,
    ACTIONS(119), 1,
      sym_type,
  [212] = 1,
    ACTIONS(121), 1,
      sym_type,
  [216] = 1,
    ACTIONS(123), 1,
      sym_type,
  [220] = 1,
    ACTIONS(125), 1,
      sym_type,
  [224] = 1,
    ACTIONS(127), 1,
      sym_type,
  [228] = 1,
    ACTIONS(129), 1,
      sym_type,
  [232] = 1,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
  [236] = 1,
    ACTIONS(133), 1,
      sym_type,
  [240] = 1,
    ACTIONS(135), 1,
      sym_type,
  [244] = 1,
    ACTIONS(137), 1,
      sym_type,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 19,
  [SMALL_STATE(12)] = 38,
  [SMALL_STATE(13)] = 48,
  [SMALL_STATE(14)] = 58,
  [SMALL_STATE(15)] = 68,
  [SMALL_STATE(16)] = 78,
  [SMALL_STATE(17)] = 88,
  [SMALL_STATE(18)] = 98,
  [SMALL_STATE(19)] = 108,
  [SMALL_STATE(20)] = 118,
  [SMALL_STATE(21)] = 128,
  [SMALL_STATE(22)] = 138,
  [SMALL_STATE(23)] = 148,
  [SMALL_STATE(24)] = 158,
  [SMALL_STATE(25)] = 168,
  [SMALL_STATE(26)] = 178,
  [SMALL_STATE(27)] = 188,
  [SMALL_STATE(28)] = 198,
  [SMALL_STATE(29)] = 208,
  [SMALL_STATE(30)] = 212,
  [SMALL_STATE(31)] = 216,
  [SMALL_STATE(32)] = 220,
  [SMALL_STATE(33)] = 224,
  [SMALL_STATE(34)] = 228,
  [SMALL_STATE(35)] = 232,
  [SMALL_STATE(36)] = 236,
  [SMALL_STATE(37)] = 240,
  [SMALL_STATE(38)] = 244,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 8),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 4, 0, 8),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 3, 0, 2),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 3, 0, 2),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_parts, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_parts, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 2, 0, 1),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 2, 0, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 3, 0, 4),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 3, 0, 4),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 3, 0, 3),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 3, 0, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 3, 0, 5),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 3, 0, 5),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 6),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 4, 0, 6),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 7),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 4, 0, 7),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 5, 0, 14),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 5, 0, 14),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 5, 0, 13),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 5, 0, 13),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 9),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 4, 0, 9),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 5, 0, 15),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 5, 0, 15),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 10),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 4, 0, 10),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 11),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 4, 0, 11),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 5, 0, 12),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 5, 0, 12),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 6, 0, 16),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 6, 0, 16),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_size, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [131] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_printf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
